interface Horse {
    id: string,
    harasid: string
    name: string,
    breed: string,
    gender: string,
    birthYear: number,
    color: string,
    mother: string,
    father: string,
    trainedFor: string,
    healthStatus: string,
    description: string,
}

interface Haras {
    id: string,
    type: string,
    name: string,
    description: string,
    location?: string,
}

export const haras : Haras[] = [
  {
    id: "1",
    type: "haras",
    name: "Anadolu",
    description: "Yarış atları harası",
    location: "Sakarya",
  },
  {
    id: "2",
    type: "haras",
    name: "Yörük",
    description: "Gösteri atları harası",
    location: "Bursa",
  },
]
export const horses: Horse[] = [
  {
    id: "1",
    harasid: "1",
    name: "Alaz",
    breed: "Arap",
    gender: "Erkek",
    birthYear: 2017,
    color: "Kır",
    mother: "Güneş",
    father: "Kasırga",
    trainedFor: "Yarış",
    healthStatus: "Sağlıklı",
    description: "Çok enerjik, yüksek hız potansiyeli var.",
  },
  {
    id: "2",
    harasid: "1",
    name: "Yıldız",
    breed: "İngiliz",
    gender: "Dişi",
    birthYear: 2018,
    color: "Doru",
    mother: "Peri",
    father: "Şimşek",
    trainedFor: "Binicilik",
    healthStatus: "Sağlıklı",
    description: "Uysal yapısı ile yeni başlayanlar için ideal.",
  },
  {
    id: "3",
    harasid: "1",
    name: "Pars",
    breed: "Haflinger",
    gender: "Erkek",
    birthYear: 2016,
    color: "Al",
    mother: "Luna",
    father: "Volkan",
    trainedFor: "Terapötik Binicilik",
    healthStatus: "Sağlıklı",
    description: "Çocuklarla çok iyi anlaşır.",
  },
  {
    id: "4",
    harasid: "1",
    name: "Zümrüt",
    breed: "Arap",
    gender: "Dişi",
    birthYear: 2019,
    color: "Yağız",
    mother: "Kardelen",
    father: "Asil",
    trainedFor: "Gösteri",
    healthStatus: "Sağlıklı",
    description: "İleri düzey eğitimli, yarışlara da katılmıştır.",
  },
  {
    id: "5",
    harasid: "1",
    name: "Fırtına",
    breed: "Quarter",
    gender: "Erkek",
    birthYear: 2015,
    color: "Kır",
    mother: "Lale",
    father: "Rüzgar",
    trainedFor: "Rodeo",
    healthStatus: "Sol arka dizinde geçmiş bir sakatlık var",
    description: "Sert zemin koşularına dikkat edilmeli.",
  },
   {
    id: "6",
    harasid: "1",
    name: "Alaz",
    breed: "Arap",
    gender: "Erkek",
    birthYear: 2017,
    color: "Kır",
    mother: "Güneş",
    father: "Kasırga",
    trainedFor: "Yarış",
    healthStatus: "Sağlıklı",
    description: "Çok enerjik, yüksek hız potansiyeli var.",
  },
  {
    id: "7",
    harasid: "1",
    name: "Yıldız",
    breed: "İngiliz",
    gender: "Dişi",
    birthYear: 2018,
    color: "Doru",
    mother: "Peri",
    father: "Şimşek",
    trainedFor: "Binicilik",
    healthStatus: "Sağlıklı",
    description: "Uysal yapısı ile yeni başlayanlar için ideal.",
  },
  {
    id: "8",
    harasid: "1",
    name: "Pars",
    breed: "Haflinger",
    gender: "Erkek",
    birthYear: 2016,
    color: "Al",
    mother: "Luna",
    father: "Volkan",
    trainedFor: "Terapötik Binicilik",
    healthStatus: "Sağlıklı",
    description: "Çocuklarla çok iyi anlaşır.",
  },
  {
    id: "9",
    harasid: "2",
    name: "Zümrüt",
    breed: "Arap",
    gender: "Dişi",
    birthYear: 2019,
    color: "Yağız",
    mother: "Kardelen",
    father: "Asil",
    trainedFor: "Gösteri",
    healthStatus: "Sağlıklı",
    description: "İleri düzey eğitimli, yarışlara da katılmıştır.",
  },
  {
    id: "10",
    harasid: "2",
    name: "Fırtına",
    breed: "Quarter",
    gender: "Erkek",
    birthYear: 2015,
    color: "Kır",
    mother: "Lale",
    father: "Rüzgar",
    trainedFor: "Rodeo",
    healthStatus: "Sol arka dizinde geçmiş bir sakatlık var",
    description: "Sert zemin koşularına dikkat edilmeli.",
  },
   {
    id: "11",
    harasid: "2",
    name: "Alaz",
    breed: "Arap",
    gender: "Erkek",
    birthYear: 2017,
    color: "Kır",
    mother: "Güneş",
    father: "Kasırga",
    trainedFor: "Yarış",
    healthStatus: "Sağlıklı",
    description: "Çok enerjik, yüksek hız potansiyeli var.",
  },
  {
    id: "12",
    harasid: "2",
    name: "Yıldız",
    breed: "İngiliz",
    gender: "Dişi",
    birthYear: 2018,
    color: "Doru",
    mother: "Peri",
    father: "Şimşek",
    trainedFor: "Binicilik",
    healthStatus: "Sağlıklı",
    description: "Uysal yapısı ile yeni başlayanlar için ideal.",
  },
  {
    id: "13",
    harasid: "2",
    name: "Pars",
    breed: "Haflinger",
    gender: "Erkek",
    birthYear: 2016,
    color: "Al",
    mother: "Luna",
    father: "Volkan",
    trainedFor: "Terapötik Binicilik",
    healthStatus: "Sağlıklı",
    description: "Çocuklarla çok iyi anlaşır.",
  },
  {
    id: "14",
    harasid: "2",
    name: "Zümrüt",
    breed: "Arap",
    gender: "Dişi",
    birthYear: 2019,
    color: "Yağız",
    mother: "Kardelen",
    father: "Asil",
    trainedFor: "Gösteri",
    healthStatus: "Sağlıklı",
    description: "İleri düzey eğitimli, yarışlara da katılmıştır.",
  },
  {
    id: "15",
    harasid: "2",
    name: "Fırtına",
    breed: "Quarter",
    gender: "Erkek",
    birthYear: 2015,
    color: "Kır",
    mother: "Lale",
    father: "Rüzgar",
    trainedFor: "Rodeo",
    healthStatus: "Sol arka dizinde geçmiş bir sakatlık var",
    description: "Sert zemin koşularına dikkat edilmeli.",
  },
    {
    id: "16",
    harasid: "2",
    name: "Yağmur",
    breed: "Quarter",
    gender: "Dişi",
    birthYear: 2015,
    color: "Kır",
    mother: "Lale",
    father: "Rüzgar",
    trainedFor: "Gösteri",
    healthStatus: "Sağlıklı",
    description: "Uysal yapısı ile yeni başlayanlar için ideal.",
  },
];
